#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pyfakefs
Version  : 5.0.0
Release  : 19
URL      : https://files.pythonhosted.org/packages/5a/50/a33e45dc6d7e12b652e32716688a509f341f75b19086141ed21938c82686/pyfakefs-5.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/5a/50/a33e45dc6d7e12b652e32716688a509f341f75b19086141ed21938c82686/pyfakefs-5.0.0.tar.gz
Summary  : pyfakefs implements a fake file system that mocks the Python file system modules.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-pyfakefs-license = %{version}-%{release}
Requires: pypi-pyfakefs-python = %{version}-%{release}
Requires: pypi-pyfakefs-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# pyfakefs [![PyPI version](https://badge.fury.io/py/pyfakefs.svg)](https://badge.fury.io/py/pyfakefs) [![Python version](https://img.shields.io/pypi/pyversions/pyfakefs.svg)](https://img.shields.io/pypi/pyversions/pyfakefs.svg) ![Testsuite](https://github.com/pytest-dev/pyfakefs/workflows/Testsuite/badge.svg) [![Documentation Status](https://readthedocs.org/projects/pytest-pyfakefs/badge/?version=latest)](https://pytest-pyfakefs.readthedocs.io/en/latest/?badge=latest)

%package license
Summary: license components for the pypi-pyfakefs package.
Group: Default

%description license
license components for the pypi-pyfakefs package.


%package python
Summary: python components for the pypi-pyfakefs package.
Group: Default
Requires: pypi-pyfakefs-python3 = %{version}-%{release}

%description python
python components for the pypi-pyfakefs package.


%package python3
Summary: python3 components for the pypi-pyfakefs package.
Group: Default
Requires: python3-core
Provides: pypi(pyfakefs)

%description python3
python3 components for the pypi-pyfakefs package.


%prep
%setup -q -n pyfakefs-5.0.0
cd %{_builddir}/pyfakefs-5.0.0
pushd ..
cp -a pyfakefs-5.0.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1665420235
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pyfakefs
cp %{_builddir}/pyfakefs-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pypi-pyfakefs/57aed0b0f74e63f6b85cce11bce29ba1710b422b || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pyfakefs/57aed0b0f74e63f6b85cce11bce29ba1710b422b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
